### PR TITLE
Add standard-app-packages to package dependencies Fix #4

### LINKED ISSUE #4: Deps is not defined
Using paginated-subscription from inside a private package I get error:

```
Uncaught ReferenceError: Deps is not defined 
```

Adding the following to paginated-subscription/package.js

```
api.use('standard-app-packages');
```

Solved for me locally.

### PR DESCRIPTION
**Pull request by aaronjudd**
Needed when using pagination package in private/other packages

### CODE REVIEW

**Comment by tmeasday** [comment]
Hmm. I'm not really comfortable depending on _all_ the standard packages.

Can you let me know how to reproduce the problem in #4 ?

**Comment by aaronjudd** [comment]
I've written a completely empty project locally that only has paginated used in a package.. and everything seems to work fine, so I'm debugging further to see why my code is having the issue.  Since the test project works, I'm going to say we can close this, and I'll let you know once I find the root cause, and am able to replicate in the test project.

**Comment by tmeasday** [comment]
Ok, sounds reasonable.

**Comment by boboci9** [comment]
Hi @aaronjudd,

Have you found a way to make this package work with the RC packages? I have the same issue as you had I think, I added all dependencies to the packages.js:

```
api.use([
    'deps',
    'standard-app-packages',
], ["client", "server"]);
api.use([
    'tmeasday:paginated-subscription',
    ], "client");
```

But I still get the error: 
`Uncaught ReferenceError: Deps is not defined`

Thanks for your help.

**Pull request closed without merging**
